name: IIS-CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: publish

      - name: Verify Artifact
        shell: powershell
        run: |
          Write-Host "Published files:"
          Get-ChildItem publish -Recurse

      - name: Deploy to IIS using MSDeploy
        shell: powershell
        run: |
          $msdeploy = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"

          & $msdeploy `
            -verb:sync `
            -source:contentPath="publish" `
            -dest:contentPath="DemoApi",computerName="https://${{ secrets.IIS_SERVER }}:8172/msdeploy.axd?site=DemoApi",userName="${{ secrets.IIS_USERNAME }}",password="${{ secrets.IIS_PASSWORD }}",authType="Basic" `
            -allowUntrusted

      - name: Restart IIS Site
        shell: powershell
        run: |
          Import-Module WebAdministration
          Restart-WebAppPool -Name "DemoApiPool"