name: IIS-CI-CD

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish Application
        run: dotnet publish DemoApi/DemoApi.csproj -c Release -o publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish

  deploy:
    needs: build
    runs-on: [self-hosted, windows]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: publish

      - name: Verify Published Files
        shell: powershell
        run: |
          Write-Host "Published files:"
          Get-ChildItem publish -Recurse

      - name: Locate MSDeploy
        shell: powershell
        run: |
          Get-ChildItem "C:\Program Files*\IIS" -Recurse -Filter msdeploy.exe

      - name: Deploy to IIS using MSDeploy
        shell: powershell
        run: |

          $msdeploy = Get-ChildItem `
            "C:\Program Files*\IIS" `
            -Recurse `
            -Filter msdeploy.exe `
            | Select-Object -First 1 -ExpandProperty FullName

          $publishPath = (Resolve-Path ".\publish").Path

          Write-Host "MSDeploy Path: $msdeploy"
          Write-Host "Publish Path: $publishPath"

          & $msdeploy `
            -verb:sync `
            -source:contentPath="$publishPath" `
            -dest:contentPath="DemoApi",computerName="https://${{ secrets.IIS_SERVER }}:8172/msdeploy.axd?site=DemoApi",userName="${{ secrets.IIS_USERNAME }}",password="${{ secrets.IIS_PASSWORD }}",authType="Basic" `
            -allowUntrusted `
            -disableLink:AppPoolExtension `
            -disableLink:ContentExtension `
            -disableLink:CertificateExtension

      - name: Restart IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Restart-WebAppPool -Name "DemoApiPool"