name: IIS-CI-CD

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish Application
        run: dotnet publish DemoApi/DemoApi.csproj -c Release -o publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish

  deploy:
    needs: build
    runs-on: [self-hosted, windows]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: publish

      - name: Setup SSH Key
        shell: powershell
        run: |
          mkdir $env:USERPROFILE\.ssh -Force

          "${{ secrets.SSH_PRIVATE_KEY }}" | Out-File $env:USERPROFILE\.ssh\id_rsa -Encoding ascii

      - name: Stop IIS Site
        shell: powershell
        run: |
          try {
            ssh -o StrictHostKeyChecking=no `
            -i $env:USERPROFILE\.ssh\id_rsa `
            ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} `
            'powershell "Import-Module WebAdministration; Stop-Website -Name ''DemoApi''; Stop-WebAppPool -Name ''DemoApiPool''"'
          }
          catch {
            Write-Host "Ignoring stop errors..."
          }

          exit 0

      - name: Copy Files To IIS VM
        shell: powershell
        run: |
          scp -o StrictHostKeyChecking=no `
          -i $env:USERPROFILE\.ssh\id_rsa `
          -r publish/* `
          ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:/c:/inetpub/DemoApi/

      - name: Start IIS Site
        shell: powershell
        run: |
          ssh -o StrictHostKeyChecking=no `
          -i $env:USERPROFILE\.ssh\id_rsa `
          ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} `
          'powershell "Import-Module WebAdministration; Start-WebAppPool -Name ''DemoApiPool''; Start-Website -Name ''DemoApi''"'